# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

defaults:
  run:
    shell: bash
    working-directory: plugins/file-upload

on:
  push:
    branches: [ "master", plugins-file-upload-salesforce ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run build --if-present
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: file-upload.webchat-plugin.js
        path: dist/file-upload.webchat-plugin.js 
